### ISSUE TITLE
Scroll content

### ISSUE THREAD

**Issue by mikestreety** [tobiasahlin/animated-menu#3]
Nice effect and lovely menu!

I was just having a play around and noticed you have `overflow: hidden` on the body, which means when your site content goes beyond the "fold", you can't scroll.

I would suggest a minor improvement.

Add a class to the body when the menu is open and use that to open the menu. The JS would be

``` js
$(function() {

  $(".menu-link").click(function(e) {
    e.preventDefault();
    $("body").toggleClass("menu-open");
  });

});
```

And an update to the css:

``` css
body {
  margin: 0;
  padding: 0;
  background-color: #ff685d;
  font-family: Helvetica Neue, arial, sans-serif;
  color: #fff;
}

body.menu-open {
    overflow: hidden;
}
```

You would then just need to change where you have `.menu.open .menu-circle` to `.menu-open .menu-circle` and the same with the overlay.

Other than that it's a lovely effect!
